services:
  app:
    build: .
    container_name: minesweeper
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=minesweeper.kuuhaku.dev
      - VIRTUAL_PORT=3000
    expose:
      - 3000
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
